<?php

namespace Database\Seeders;

use App\Domains\Vendor\Models\City;
use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $jsonObject = '[

                {"id":"1","state_id":"1","country_id":"1","name":{"ar":"15 مايو","en":"15 May"}},
                {"id":"2","state_id":"1","country_id":"1","name":{"ar":"الازبكية","en":"Al Azbakeyah"}},
                {"id":"3","state_id":"1","country_id":"1","name":{"ar":"البساتين","en":"Al Basatin"}},
                {"id":"4","state_id":"1","country_id":"1","name":{"ar":"التبين","en":"Tebin"}},
                {"id":"5","state_id":"1","country_id":"1","name":{"ar":"الخليفة","en":"El-Khalifa"}},
                {"id":"6","state_id":"1","country_id":"1","name":{"ar":"الدراسة","en":"El darrasa"}},
                {"id":"7","state_id":"1","country_id":"1","name":{"ar":"الدرب الاحمر","en":"Aldarb Alahmar"}},
                {"id":"8","state_id":"1","country_id":"1","name":{"ar":"الزاوية الحمراء","en":"Zawya al-Hamra"}},
                {"id":"9","state_id":"1","country_id":"1","name":{"ar":"الزيتون","en":"El-Zaytoun"}},
                {"id":"10","state_id":"1","country_id":"1","name":{"ar":"الساحل","en":"Sahel"}},
                {"id":"11","state_id":"1","country_id":"1","name":{"ar":"السلام","en":"El Salam"}},
                {"id":"12","state_id":"1","country_id":"1","name":{"ar":"السيدة زينب","en":"Sayeda Zeinab"}},
                {"id":"13","state_id":"1","country_id":"1","name":{"ar":"الشرابية","en":"El Sharabeya"}},
                {"id":"14","state_id":"1","country_id":"1","name":{"ar":"مدينة الشروق","en":"Shorouk"}},
                {"id":"15","state_id":"1","country_id":"1","name":{"ar":"الظاهر","en":"El Daher"}},
                {"id":"16","state_id":"1","country_id":"1","name":{"ar":"العتبة","en":"Ataba"}},
                {"id":"17","state_id":"1","country_id":"1","name":{"ar":"القاهرة الجديدة","en":"New Cairo"}},
                {"id":"18","state_id":"1","country_id":"1","name":{"ar":"المرج","en":"El Marg"}},
                {"id":"19","state_id":"1","country_id":"1","name":{"ar":"عزبة النخل","en":"Ezbet el Nakhl"}},
                {"id":"20","state_id":"1","country_id":"1","name":{"ar":"المطرية","en":"Matareya"}},
                {"id":"21","state_id":"1","country_id":"1","name":{"ar":"المعادى","en":"Maadi"}},
                {"id":"22","state_id":"1","country_id":"1","name":{"ar":"المعصرة","en":"Maasara"}},
                {"id":"23","state_id":"1","country_id":"1","name":{"ar":"المقطم","en":"Mokattam"}},
                {"id":"24","state_id":"1","country_id":"1","name":{"ar":"المنيل","en":"Manyal"}},
                {"id":"25","state_id":"1","country_id":"1","name":{"ar":"الموسكى","en":"Mosky"}},
                {"id":"26","state_id":"1","country_id":"1","name":{"ar":"النزهة","en":"Nozha"}},
                {"id":"27","state_id":"1","country_id":"1","name":{"ar":"الوايلى","en":"Waily"}},
                {"id":"28","state_id":"1","country_id":"1","name":{"ar":"باب الشعرية","en":"Bab al-Shereia"}},
                {"id":"29","state_id":"1","country_id":"1","name":{"ar":"بولاق","en":"Bolaq"}},
                {"id":"30","state_id":"1","country_id":"1","name":{"ar":"جاردن سيتى","en":"Garden City"}},
                {"id":"31","state_id":"1","country_id":"1","name":{"ar":"حدائق القبة","en":"Hadayek El-Kobba"}},
                {"id":"32","state_id":"1","country_id":"1","name":{"ar":"حلوان","en":"Helwan"}},
                {"id":"33","state_id":"1","country_id":"1","name":{"ar":"دار السلام","en":"Dar Al Salam"}},
                {"id":"34","state_id":"1","country_id":"1","name":{"ar":"شبرا","en":"Shubra"}},
                {"id":"35","state_id":"1","country_id":"1","name":{"ar":"طره","en":"Tura"}},
                {"id":"36","state_id":"1","country_id":"1","name":{"ar":"عابدين","en":"Abdeen"}},
                {"id":"37","state_id":"1","country_id":"1","name":{"ar":"عباسية","en":"Abaseya"}},
                {"id":"38","state_id":"1","country_id":"1","name":{"ar":"عين شمس","en":"Ain Shams"}},
                {"id":"39","state_id":"1","country_id":"1","name":{"ar":"مدينة نصر","en":"Nasr City"}},
                {"id":"40","state_id":"1","country_id":"1","name":{"ar":"مصر الجديدة","en":"New Heliopolis"}},
                {"id":"41","state_id":"1","country_id":"1","name":{"ar":"مصر القديمة","en":"Masr Al Qadima"}},
                {"id":"42","state_id":"1","country_id":"1","name":{"ar":"منشية ناصر","en":"Mansheya Nasir"}},
                {"id":"43","state_id":"1","country_id":"1","name":{"ar":"مدينة بدر","en":"Badr City"}},
                {"id":"44","state_id":"1","country_id":"1","name":{"ar":"مدينة العبور","en":"Obour City"}},
                {"id":"45","state_id":"1","country_id":"1","name":{"ar":"وسط البلد","en":"Cairo Downtown"}},
                {"id":"46","state_id":"1","country_id":"1","name":{"ar":"الزمالك","en":"Zamalek"}},
                {"id":"47","state_id":"1","country_id":"1","name":{"ar":"قصر النيل","en":"Kasr El Nile"}},
                {"id":"48","state_id":"1","country_id":"1","name":{"ar":"الرحاب","en":"Rehab"}},
                {"id":"49","state_id":"1","country_id":"1","name":{"ar":"القطامية","en":"Katameya"}},
                {"id":"50","state_id":"1","country_id":"1","name":{"ar":"مدينتي","en":"Madinty"}},
                {"id":"51","state_id":"1","country_id":"1","name":{"ar":"روض الفرج","en":"Rod Alfarag"}},
                {"id":"52","state_id":"1","country_id":"1","name":{"ar":"شيراتون","en":"Sheraton"}},
                {"id":"53","state_id":"1","country_id":"1","name":{"ar":"الجمالية","en":"El-Gamaleya"}},
                {"id":"54","state_id":"1","country_id":"1","name":{"ar":"العاشر من رمضان","en":"10th of Ramadan City"}},
                {"id":"55","state_id":"1","country_id":"1","name":{"ar":"الحلمية","en":"Helmeyat Alzaytoun"}},
                {"id":"56","state_id":"1","country_id":"1","name":{"ar":"النزهة الجديدة","en":"New Nozha"}},
                {"id":"57","state_id":"1","country_id":"1","name":{"ar":"العاصمة الإدارية","en":"Capital New"}},
                {"id":"58","state_id":"2","country_id":"1","name":{"ar":"الجيزة","en":"Giza"}},
                {"id":"59","state_id":"2","country_id":"1","name":{"ar":"السادس من أكتوبر","en":"Sixth of October"}},
                {"id":"60","state_id":"2","country_id":"1","name":{"ar":"الشيخ زايد","en":"Cheikh Zayed"}},
                {"id":"61","state_id":"2","country_id":"1","name":{"ar":"الحوامدية","en":"Hawamdiyah"}},
                {"id":"62","state_id":"2","country_id":"1","name":{"ar":"البدرشين","en":"Al Badrasheen"}},
                {"id":"63","state_id":"2","country_id":"1","name":{"ar":"الصف","en":"Saf"}},
                {"id":"64","state_id":"2","country_id":"1","name":{"ar":"أطفيح","en":"Atfih"}},
                {"id":"65","state_id":"2","country_id":"1","name":{"ar":"العياط","en":"Al Ayat"}},
                {"id":"66","state_id":"2","country_id":"1","name":{"ar":"الباويطي","en":"Al-Bawaiti"}},
                {"id":"67","state_id":"2","country_id":"1","name":{"ar":"منشأة القناطر","en":"ManshiyetAl Qanater"}},
                {"id":"68","state_id":"2","country_id":"1","name":{"ar":"أوسيم","en":"Oaseem"}},
                {"id":"69","state_id":"2","country_id":"1","name":{"ar":"كرداسة","en":"Kerdasa"}},
                {"id":"70","state_id":"2","country_id":"1","name":{"ar":"أبو النمرس","en":"Abu Nomros"}},
                {"id":"71","state_id":"2","country_id":"1","name":{"ar":"كفر غطاطي","en":"Kafr Ghati"}},
                {"id":"72","state_id":"2","country_id":"1","name":{"ar":"منشأة البكاري","en":"Manshiyet Al Bakari"}},
                {"id":"73","state_id":"2","country_id":"1","name":{"ar":"الدقى","en":"Dokki"}},
                {"id":"74","state_id":"2","country_id":"1","name":{"ar":"العجوزة","en":"Agouza"}},
                {"id":"75","state_id":"2","country_id":"1","name":{"ar":"الهرم","en":"Haram"}},
                {"id":"76","state_id":"2","country_id":"1","name":{"ar":"الوراق","en":"Warraq"}},
                {"id":"77","state_id":"2","country_id":"1","name":{"ar":"امبابة","en":"Imbaba"}},
                {"id":"78","state_id":"2","country_id":"1","name":{"ar":"بولاق الدكرور","en":"Boulaq Dakrour"}},
                {"id":"79","state_id":"2","country_id":"1","name":{"ar":"الواحات البحرية","en":"Al Wahat Al Baharia"}},
                {"id":"80","state_id":"2","country_id":"1","name":{"ar":"العمرانية","en":"Omraneya"}},
                {"id":"81","state_id":"2","country_id":"1","name":{"ar":"المنيب","en":"Moneeb"}},
                {"id":"82","state_id":"2","country_id":"1","name":{"ar":"بين السرايات","en":"Bin Alsarayat"}},
                {"id":"83","state_id":"2","country_id":"1","name":{"ar":"الكيت كات","en":"Kit Kat"}},
                {"id":"84","state_id":"2","country_id":"1","name":{"ar":"المهندسين","en":"Mohandessin"}},
                {"id":"85","state_id":"2","country_id":"1","name":{"ar":"فيصل","en":"Faisal"}},
                {"id":"86","state_id":"2","country_id":"1","name":{"ar":"أبو رواش","en":"Abu Rawash"}},
                {"id":"87","state_id":"2","country_id":"1","name":{"ar":"حدائق الأهرام","en":"Hadayek Alahram"}},
                {"id":"88","state_id":"2","country_id":"1","name":{"ar":"الحرانية","en":"Haraneya"}},
                {"id":"89","state_id":"2","country_id":"1","name":{"ar":"حدائق اكتوبر","en":"Hadayek October"}},
                {"id":"90","state_id":"2","country_id":"1","name":{"ar":"صفط اللبن","en":"Saft Allaban"}},
                {"id":"91","state_id":"2","country_id":"1","name":{"ar":"القرية الذكية","en":"Smart Village"}},
                {"id":"92","state_id":"2","country_id":"1","name":{"ar":"ارض اللواء","en":"Ard Ellwaa"}},
                {"id":"93","state_id":"3","country_id":"1","name":{"ar":"ابو قير","en":"Abu Qir"}},
                {"id":"94","state_id":"3","country_id":"1","name":{"ar":"الابراهيمية","en":"Al Ibrahimeyah"}},
                {"id":"95","state_id":"3","country_id":"1","name":{"ar":"الأزاريطة","en":"Azarita"}},
                {"id":"96","state_id":"3","country_id":"1","name":{"ar":"الانفوشى","en":"Anfoushi"}},
                {"id":"97","state_id":"3","country_id":"1","name":{"ar":"الدخيلة","en":"Dekheila"}},
                {"id":"98","state_id":"3","country_id":"1","name":{"ar":"السيوف","en":"El Soyof"}},
                {"id":"99","state_id":"3","country_id":"1","name":{"ar":"العامرية","en":"Ameria"}},
                {"id":"100","state_id":"3","country_id":"1","name":{"ar":"اللبان","en":"El Labban"}},
                {"id":"101","state_id":"3","country_id":"1","name":{"ar":"المفروزة","en":"Al Mafrouza"}},
                {"id":"102","state_id":"3","country_id":"1","name":{"ar":"المنتزه","en":"El Montaza"}},
                {"id":"103","state_id":"3","country_id":"1","name":{"ar":"المنشية","en":"Mansheya"}},
                {"id":"104","state_id":"3","country_id":"1","name":{"ar":"الناصرية","en":"Naseria"}},
                {"id":"105","state_id":"3","country_id":"1","name":{"ar":"امبروزو","en":"Ambrozo"}},
                {"id":"106","state_id":"3","country_id":"1","name":{"ar":"باب شرق","en":"Bab Sharq"}},
                {"id":"107","state_id":"3","country_id":"1","name":{"ar":"برج العرب","en":"Bourj Alarab"}},
                {"id":"108","state_id":"3","country_id":"1","name":{"ar":"ستانلى","en":"Stanley"}},
                {"id":"109","state_id":"3","country_id":"1","name":{"ar":"سموحة","en":"Smouha"}},
                {"id":"110","state_id":"3","country_id":"1","name":{"ar":"سيدى بشر","en":"Sidi Bishr"}},
                {"id":"111","state_id":"3","country_id":"1","name":{"ar":"شدس","en":"Shads"}},
                {"id":"112","state_id":"3","country_id":"1","name":{"ar":"غيط العنب","en":"Gheet Alenab"}},
                {"id":"113","state_id":"3","country_id":"1","name":{"ar":"فلمينج","en":"Fleming"}},
                {"id":"114","state_id":"3","country_id":"1","name":{"ar":"فيكتوريا","en":"Victoria"}},
                {"id":"115","state_id":"3","country_id":"1","name":{"ar":"كامب شيزار","en":"Camp Shizar"}},
                {"id":"116","state_id":"3","country_id":"1","name":{"ar":"كرموز","en":"Karmooz"}},
                {"id":"117","state_id":"3","country_id":"1","name":{"ar":"محطة الرمل","en":"Mahta Alraml"}},
                {"id":"118","state_id":"3","country_id":"1","name":{"ar":"مينا البصل","en":"Mina El-Basal"}},
                {"id":"119","state_id":"3","country_id":"1","name":{"ar":"العصافرة","en":"Asafra"}},
                {"id":"120","state_id":"3","country_id":"1","name":{"ar":"العجمي","en":"Agamy"}},
                {"id":"121","state_id":"3","country_id":"1","name":{"ar":"بكوس","en":"Bakos"}},
                {"id":"122","state_id":"3","country_id":"1","name":{"ar":"بولكلي","en":"Boulkly"}},
                {"id":"123","state_id":"3","country_id":"1","name":{"ar":"كليوباترا","en":"Cleopatra"}},
                {"id":"124","state_id":"3","country_id":"1","name":{"ar":"جليم","en":"Glim"}},
                {"id":"125","state_id":"3","country_id":"1","name":{"ar":"المعمورة","en":"Al Mamurah"}},
                {"id":"126","state_id":"3","country_id":"1","name":{"ar":"المندرة","en":"Al Mandara"}},
                {"id":"127","state_id":"3","country_id":"1","name":{"ar":"محرم بك","en":"Moharam Bek"}},
                {"id":"128","state_id":"3","country_id":"1","name":{"ar":"الشاطبي","en":"Elshatby"}},
                {"id":"129","state_id":"3","country_id":"1","name":{"ar":"سيدي جابر","en":"Sidi Gaber"}},
                {"id":"130","state_id":"3","country_id":"1","name":{"ar":"الساحل الشمالي","en":"North Coast\/sahel"}},
                {"id":"131","state_id":"3","country_id":"1","name":{"ar":"الحضرة","en":"Alhadra"}},
                {"id":"132","state_id":"3","country_id":"1","name":{"ar":"العطارين","en":"Alattarin"}},
                {"id":"133","state_id":"3","country_id":"1","name":{"ar":"سيدي كرير","en":"Sidi Kerir"}},
                {"id":"134","state_id":"3","country_id":"1","name":{"ar":"الجمرك","en":"Elgomrok"}},
                {"id":"135","state_id":"3","country_id":"1","name":{"ar":"المكس","en":"Al Max"}},
                {"id":"136","state_id":"3","country_id":"1","name":{"ar":"مارينا","en":"Marina"}},
                {"id":"137","state_id":"4","country_id":"1","name":{"ar":"المنصورة","en":"Mansoura"}},
                {"id":"138","state_id":"4","country_id":"1","name":{"ar":"طلخا","en":"Talkha"}},
                {"id":"139","state_id":"4","country_id":"1","name":{"ar":"ميت غمر","en":"Mitt Ghamr"}},
                {"id":"140","state_id":"4","country_id":"1","name":{"ar":"دكرنس","en":"Dekernes"}},
                {"id":"141","state_id":"4","country_id":"1","name":{"ar":"أجا","en":"Aga"}},
                {"id":"142","state_id":"4","country_id":"1","name":{"ar":"منية النصر","en":"Menia El Nasr"}},
                {"id":"143","state_id":"4","country_id":"1","name":{"ar":"السنبلاوين","en":"Sinbillawin"}},
                {"id":"144","state_id":"4","country_id":"1","name":{"ar":"الكردي","en":"El Kurdi"}},
                {"id":"145","state_id":"4","country_id":"1","name":{"ar":"بني عبيد","en":"Bani Ubaid"}},
                {"id":"146","state_id":"4","country_id":"1","name":{"ar":"المنزلة","en":"Al Manzala"}},
                {"id":"147","state_id":"4","country_id":"1","name":{"ar":"تمي الأمديد","en":"tami al amdid"}},
                {"id":"148","state_id":"4","country_id":"1","name":{"ar":"الجمالية","en":"aljamalia"}},
                {"id":"149","state_id":"4","country_id":"1","name":{"ar":"شربين","en":"Sherbin"}},
                {"id":"150","state_id":"4","country_id":"1","name":{"ar":"المطرية","en":"Mataria"}},
                {"id":"151","state_id":"4","country_id":"1","name":{"ar":"بلقاس","en":"Belqas"}},
                {"id":"152","state_id":"4","country_id":"1","name":{"ar":"ميت سلسيل","en":"Meet Salsil"}},
                {"id":"153","state_id":"4","country_id":"1","name":{"ar":"جمصة","en":"Gamasa"}},
                {"id":"154","state_id":"4","country_id":"1","name":{"ar":"محلة دمنة","en":"Mahalat Damana"}},
                {"id":"155","state_id":"4","country_id":"1","name":{"ar":"نبروه","en":"Nabroh"}},
                {"id":"156","state_id":"5","country_id":"1","name":{"ar":"الغردقة","en":"Hurghada"}},
                {"id":"157","state_id":"5","country_id":"1","name":{"ar":"رأس غارب","en":"Ras Ghareb"}},
                {"id":"158","state_id":"5","country_id":"1","name":{"ar":"سفاجا","en":"Safaga"}},
                {"id":"159","state_id":"5","country_id":"1","name":{"ar":"القصير","en":"El Qusiar"}},
                {"id":"160","state_id":"5","country_id":"1","name":{"ar":"مرسى علم","en":"Marsa Alam"}},
                {"id":"161","state_id":"5","country_id":"1","name":{"ar":"الشلاتين","en":"Shalatin"}},
                {"id":"162","state_id":"5","country_id":"1","name":{"ar":"حلايب","en":"Halaib"}},
                {"id":"163","state_id":"5","country_id":"1","name":{"ar":"الدهار","en":"Aldahar"}},
                {"id":"164","state_id":"6","country_id":"1","name":{"ar":"دمنهور","en":"Damanhour"}},
                {"id":"165","state_id":"6","country_id":"1","name":{"ar":"كفر الدوار","en":"Kafr El Dawar"}},
                {"id":"166","state_id":"6","country_id":"1","name":{"ar":"رشيد","en":"Rashid"}},
                {"id":"167","state_id":"6","country_id":"1","name":{"ar":"إدكو","en":"Edco"}},
                {"id":"168","state_id":"6","country_id":"1","name":{"ar":"أبو المطامير","en":"Abu al-Matamir"}},
                {"id":"169","state_id":"6","country_id":"1","name":{"ar":"أبو حمص","en":"Abu Homs"}},
                {"id":"170","state_id":"6","country_id":"1","name":{"ar":"الدلنجات","en":"Delengat"}},
                {"id":"171","state_id":"6","country_id":"1","name":{"ar":"المحمودية","en":"Mahmoudiyah"}},
                {"id":"172","state_id":"6","country_id":"1","name":{"ar":"الرحمانية","en":"Rahmaniyah"}},
                {"id":"173","state_id":"6","country_id":"1","name":{"ar":"إيتاي البارود","en":"Itai Baroud"}},
                {"id":"174","state_id":"6","country_id":"1","name":{"ar":"حوش عيسى","en":"Housh Eissa"}},
                {"id":"175","state_id":"6","country_id":"1","name":{"ar":"شبراخيت","en":"Shubrakhit"}},
                {"id":"176","state_id":"6","country_id":"1","name":{"ar":"كوم حمادة","en":"Kom Hamada"}},
                {"id":"177","state_id":"6","country_id":"1","name":{"ar":"بدر","en":"Badr"}},
                {"id":"178","state_id":"6","country_id":"1","name":{"ar":"وادي النطرون","en":"Wadi Natrun"}},
                {"id":"179","state_id":"6","country_id":"1","name":{"ar":"النوبارية الجديدة","en":"New Nubaria"}},
                {"id":"180","state_id":"6","country_id":"1","name":{"ar":"النوبارية","en":"Alnoubareya"}},
                {"id":"181","state_id":"7","country_id":"1","name":{"ar":"الفيوم","en":"Fayoum"}},
                {"id":"182","state_id":"7","country_id":"1","name":{"ar":"الفيوم الجديدة","en":"Fayoum El Gedida"}},
                {"id":"183","state_id":"7","country_id":"1","name":{"ar":"طامية","en":"Tamiya"}},
                {"id":"184","state_id":"7","country_id":"1","name":{"ar":"سنورس","en":"Snores"}},
                {"id":"185","state_id":"7","country_id":"1","name":{"ar":"إطسا","en":"Etsa"}},
                {"id":"186","state_id":"7","country_id":"1","name":{"ar":"إبشواي","en":"Epschway"}},
                {"id":"187","state_id":"7","country_id":"1","name":{"ar":"يوسف الصديق","en":"Yusuf El Sediaq"}},
                {"id":"188","state_id":"7","country_id":"1","name":{"ar":"الحادقة","en":"Hadqa"}},
                {"id":"189","state_id":"7","country_id":"1","name":{"ar":"اطسا","en":"Atsa"}},
                {"id":"190","state_id":"7","country_id":"1","name":{"ar":"الجامعة","en":"Algamaa"}},
                {"id":"191","state_id":"7","country_id":"1","name":{"ar":"السيالة","en":"Sayala"}},
                {"id":"192","state_id":"8","country_id":"1","name":{"ar":"طنطا","en":"Tanta"}},
                {"id":"193","state_id":"8","country_id":"1","name":{"ar":"المحلة الكبرى","en":"Al Mahalla Al Kobra"}},
                {"id":"194","state_id":"8","country_id":"1","name":{"ar":"كفر الزيات","en":"Kafr El Zayat"}},
                {"id":"195","state_id":"8","country_id":"1","name":{"ar":"زفتى","en":"Zefta"}},
                {"id":"196","state_id":"8","country_id":"1","name":{"ar":"السنطة","en":"El Santa"}},
                {"id":"197","state_id":"8","country_id":"1","name":{"ar":"قطور","en":"Qutour"}},
                {"id":"198","state_id":"8","country_id":"1","name":{"ar":"بسيون","en":"Basion"}},
                {"id":"199","state_id":"8","country_id":"1","name":{"ar":"سمنود","en":"Samannoud"}},
                {"id":"200","state_id":"9","country_id":"1","name":{"ar":"الإسماعيلية","en":"Ismailia"}},
                {"id":"201","state_id":"9","country_id":"1","name":{"ar":"فايد","en":"Fayed"}},
                {"id":"202","state_id":"9","country_id":"1","name":{"ar":"القنطرة شرق","en":"Qantara Sharq"}},
                {"id":"203","state_id":"9","country_id":"1","name":{"ar":"القنطرة غرب","en":"Qantara Gharb"}},
                {"id":"204","state_id":"9","country_id":"1","name":{"ar":"التل الكبير","en":"El Tal El Kabier"}},
                {"id":"205","state_id":"9","country_id":"1","name":{"ar":"أبو صوير","en":"Abu Sawir"}},
                {"id":"206","state_id":"9","country_id":"1","name":{"ar":"القصاصين الجديدة","en":"Kasasien El Gedida"}},
                {"id":"207","state_id":"9","country_id":"1","name":{"ar":"نفيشة","en":"Nefesha"}},
                {"id":"208","state_id":"9","country_id":"1","name":{"ar":"الشيخ زايد","en":"Sheikh Zayed"}},
                {"id":"209","state_id":"10","country_id":"1","name":{"ar":"شبين الكوم","en":"Shbeen El Koom"}},
                {"id":"210","state_id":"10","country_id":"1","name":{"ar":"مدينة السادات","en":"Sadat City"}},
                {"id":"211","state_id":"10","country_id":"1","name":{"ar":"منوف","en":"Menouf"}},
                {"id":"212","state_id":"10","country_id":"1","name":{"ar":"سرس الليان","en":"Sars El-Layan"}},
                {"id":"213","state_id":"10","country_id":"1","name":{"ar":"أشمون","en":"Ashmon"}},
                {"id":"214","state_id":"10","country_id":"1","name":{"ar":"الباجور","en":"Al Bagor"}},
                {"id":"215","state_id":"10","country_id":"1","name":{"ar":"قويسنا","en":"Quesna"}},
                {"id":"216","state_id":"10","country_id":"1","name":{"ar":"بركة السبع","en":"Berkat El Saba"}},
                {"id":"217","state_id":"10","country_id":"1","name":{"ar":"تلا","en":"Tala"}},
                {"id":"218","state_id":"10","country_id":"1","name":{"ar":"الشهداء","en":"Al Shohada"}},
                {"id":"219","state_id":"11","country_id":"1","name":{"ar":"المنيا","en":"Minya"}},
                {"id":"220","state_id":"11","country_id":"1","name":{"ar":"المنيا الجديدة","en":"Minya El Gedida"}},
                {"id":"221","state_id":"11","country_id":"1","name":{"ar":"العدوة","en":"El Adwa"}},
                {"id":"222","state_id":"11","country_id":"1","name":{"ar":"مغاغة","en":"Magagha"}},
                {"id":"223","state_id":"11","country_id":"1","name":{"ar":"بني مزار","en":"Bani Mazar"}},
                {"id":"224","state_id":"11","country_id":"1","name":{"ar":"مطاي","en":"Mattay"}},
                {"id":"225","state_id":"11","country_id":"1","name":{"ar":"سمالوط","en":"Samalut"}},
                {"id":"226","state_id":"11","country_id":"1","name":{"ar":"المدينة الفكرية","en":"Madinat El Fekria"}},
                {"id":"227","state_id":"11","country_id":"1","name":{"ar":"ملوي","en":"Meloy"}},
                {"id":"228","state_id":"11","country_id":"1","name":{"ar":"دير مواس","en":"Deir Mawas"}},
                {"id":"229","state_id":"11","country_id":"1","name":{"ar":"ابو قرقاص","en":"Abu Qurqas"}},
                {"id":"230","state_id":"11","country_id":"1","name":{"ar":"ارض سلطان","en":"Ard Sultan"}},
                {"id":"231","state_id":"12","country_id":"1","name":{"ar":"بنها","en":"Banha"}},
                {"id":"232","state_id":"12","country_id":"1","name":{"ar":"قليوب","en":"Qalyub"}},
                {"id":"233","state_id":"12","country_id":"1","name":{"ar":"شبرا الخيمة","en":"Shubra Al Khaimah"}},
                {"id":"234","state_id":"12","country_id":"1","name":{"ar":"القناطر الخيرية","en":"Al Qanater Charity"}},
                {"id":"235","state_id":"12","country_id":"1","name":{"ar":"الخانكة","en":"Khanka"}},
                {"id":"236","state_id":"12","country_id":"1","name":{"ar":"كفر شكر","en":"Kafr Shukr"}},
                {"id":"237","state_id":"12","country_id":"1","name":{"ar":"طوخ","en":"Tukh"}},
                {"id":"238","state_id":"12","country_id":"1","name":{"ar":"قها","en":"Qaha"}},
                {"id":"239","state_id":"12","country_id":"1","name":{"ar":"العبور","en":"Obour"}},
                {"id":"240","state_id":"12","country_id":"1","name":{"ar":"الخصوص","en":"Khosous"}},
                {"id":"241","state_id":"12","country_id":"1","name":{"ar":"شبين القناطر","en":"Shibin Al Qanater"}},
                {"id":"242","state_id":"12","country_id":"1","name":{"ar":"مسطرد","en":"Mostorod"}},
                {"id":"243","state_id":"13","country_id":"1","name":{"ar":"الخارجة","en":"El Kharga"}},
                {"id":"244","state_id":"13","country_id":"1","name":{"ar":"باريس","en":"Paris"}},
                {"id":"245","state_id":"13","country_id":"1","name":{"ar":"موط","en":"Mout"}},
                {"id":"246","state_id":"13","country_id":"1","name":{"ar":"الفرافرة","en":"Farafra"}},
                {"id":"247","state_id":"13","country_id":"1","name":{"ar":"بلاط","en":"Balat"}},
                {"id":"248","state_id":"13","country_id":"1","name":{"ar":"الداخلة","en":"Dakhla"}},
                {"id":"249","state_id":"14","country_id":"1","name":{"ar":"السويس","en":"Suez"}},
                {"id":"250","state_id":"14","country_id":"1","name":{"ar":"الجناين","en":"Alganayen"}},
                {"id":"251","state_id":"14","country_id":"1","name":{"ar":"عتاقة","en":"Ataqah"}},
                {"id":"252","state_id":"14","country_id":"1","name":{"ar":"العين السخنة","en":"Ain Sokhna"}},
                {"id":"253","state_id":"14","country_id":"1","name":{"ar":"فيصل","en":"Faysal"}},
                {"id":"254","state_id":"15","country_id":"1","name":{"ar":"أسوان","en":"Aswan"}},
                {"id":"255","state_id":"15","country_id":"1","name":{"ar":"أسوان الجديدة","en":"Aswan El Gedida"}},
                {"id":"256","state_id":"15","country_id":"1","name":{"ar":"دراو","en":"Drau"}},
                {"id":"257","state_id":"15","country_id":"1","name":{"ar":"كوم أمبو","en":"Kom Ombo"}},
                {"id":"258","state_id":"15","country_id":"1","name":{"ar":"نصر النوبة","en":"Nasr Al Nuba"}},
                {"id":"259","state_id":"15","country_id":"1","name":{"ar":"كلابشة","en":"Kalabsha"}},
                {"id":"260","state_id":"15","country_id":"1","name":{"ar":"إدفو","en":"Edfu"}},
                {"id":"261","state_id":"15","country_id":"1","name":{"ar":"الرديسية","en":"Al-Radisiyah"}},
                {"id":"262","state_id":"15","country_id":"1","name":{"ar":"البصيلية","en":"Al Basilia"}},
                {"id":"263","state_id":"15","country_id":"1","name":{"ar":"السباعية","en":"Al Sibaeia"}},
                {"id":"264","state_id":"15","country_id":"1","name":{"ar":"ابوسمبل السياحية","en":"Abo Simbl Al Siyahia"}},
                {"id":"265","state_id":"15","country_id":"1","name":{"ar":"مرسى علم","en":"Marsa Alam"}},
                {"id":"266","state_id":"16","country_id":"1","name":{"ar":"أسيوط","en":"Assiut"}},
                {"id":"267","state_id":"16","country_id":"1","name":{"ar":"أسيوط الجديدة","en":"Assiut El Gedida"}},
                {"id":"268","state_id":"16","country_id":"1","name":{"ar":"ديروط","en":"Dayrout"}},
                {"id":"269","state_id":"16","country_id":"1","name":{"ar":"منفلوط","en":"Manfalut"}},
                {"id":"270","state_id":"16","country_id":"1","name":{"ar":"القوصية","en":"Qusiya"}},
                {"id":"271","state_id":"16","country_id":"1","name":{"ar":"أبنوب","en":"Abnoub"}},
                {"id":"272","state_id":"16","country_id":"1","name":{"ar":"أبو تيج","en":"Abu Tig"}},
                {"id":"273","state_id":"16","country_id":"1","name":{"ar":"الغنايم","en":"El Ghanaim"}},
                {"id":"274","state_id":"16","country_id":"1","name":{"ar":"ساحل سليم","en":"Sahel Selim"}},
                {"id":"275","state_id":"16","country_id":"1","name":{"ar":"البداري","en":"El Badari"}},
                {"id":"276","state_id":"16","country_id":"1","name":{"ar":"صدفا","en":"Sidfa"}},
                {"id":"277","state_id":"17","country_id":"1","name":{"ar":"بني سويف","en":"Bani Sweif"}},
                {"id":"278","state_id":"17","country_id":"1","name":{"ar":"بني سويف الجديدة","en":"Beni Suef El Gedida"}},
                {"id":"279","state_id":"17","country_id":"1","name":{"ar":"الواسطى","en":"Al Wasta"}},
                {"id":"280","state_id":"17","country_id":"1","name":{"ar":"ناصر","en":"Naser"}},
                {"id":"281","state_id":"17","country_id":"1","name":{"ar":"إهناسيا","en":"Ehnasia"}},
                {"id":"282","state_id":"17","country_id":"1","name":{"ar":"ببا","en":"beba"}},
                {"id":"283","state_id":"17","country_id":"1","name":{"ar":"الفشن","en":"Fashn"}},
                {"id":"284","state_id":"17","country_id":"1","name":{"ar":"سمسطا","en":"Somasta"}},
                {"id":"285","state_id":"17","country_id":"1","name":{"ar":"الاباصيرى","en":"Alabbaseri"}},
                {"id":"286","state_id":"17","country_id":"1","name":{"ar":"مقبل","en":"Mokbel"}},
                {"id":"287","state_id":"18","country_id":"1","name":{"ar":"بورسعيد","en":"PorSaid"}},
                {"id":"288","state_id":"18","country_id":"1","name":{"ar":"بورفؤاد","en":"Port Fouad"}},
                {"id":"289","state_id":"18","country_id":"1","name":{"ar":"العرب","en":"Alarab"}},
                {"id":"290","state_id":"18","country_id":"1","name":{"ar":"حى الزهور","en":"Zohour"}},
                {"id":"291","state_id":"18","country_id":"1","name":{"ar":"حى الشرق","en":"Alsharq"}},
                {"id":"292","state_id":"18","country_id":"1","name":{"ar":"حى الضواحى","en":"Aldawahi"}},
                {"id":"293","state_id":"18","country_id":"1","name":{"ar":"حى المناخ","en":"Almanakh"}},
                {"id":"294","state_id":"18","country_id":"1","name":{"ar":"حى مبارك","en":"Mubarak"}},
                {"id":"295","state_id":"19","country_id":"1","name":{"ar":"دمياط","en":"Damietta"}},
                {"id":"296","state_id":"19","country_id":"1","name":{"ar":"دمياط الجديدة","en":"New Damietta"}},
                {"id":"297","state_id":"19","country_id":"1","name":{"ar":"رأس البر","en":"Ras El Bar"}},
                {"id":"298","state_id":"19","country_id":"1","name":{"ar":"فارسكور","en":"Faraskour"}},
                {"id":"299","state_id":"19","country_id":"1","name":{"ar":"الزرقا","en":"Zarqa"}},
                {"id":"300","state_id":"19","country_id":"1","name":{"ar":"السرو","en":"alsaru"}},
                {"id":"301","state_id":"19","country_id":"1","name":{"ar":"الروضة","en":"alruwda"}},
                {"id":"302","state_id":"19","country_id":"1","name":{"ar":"كفر البطيخ","en":"Kafr El-Batikh"}},
                {"id":"303","state_id":"19","country_id":"1","name":{"ar":"عزبة البرج","en":"Azbet Al Burg"}},
                {"id":"304","state_id":"19","country_id":"1","name":{"ar":"ميت أبو غالب","en":"Meet Abou Ghalib"}},
                {"id":"305","state_id":"19","country_id":"1","name":{"ar":"كفر سعد","en":"Kafr Saad"}},
                {"id":"306","state_id":"20","country_id":"1","name":{"ar":"الزقازيق","en":"Zagazig"}},
                {"id":"307","state_id":"20","country_id":"1","name":{"ar":"العاشر من رمضان","en":"Al Ashr Men Ramadan"}},
                {"id":"308","state_id":"20","country_id":"1","name":{"ar":"منيا القمح","en":"Minya Al Qamh"}},
                {"id":"309","state_id":"20","country_id":"1","name":{"ar":"بلبيس","en":"Belbeis"}},
                {"id":"310","state_id":"20","country_id":"1","name":{"ar":"مشتول السوق","en":"Mashtoul El Souq"}},
                {"id":"311","state_id":"20","country_id":"1","name":{"ar":"القنايات","en":"Qenaiat"}},
                {"id":"312","state_id":"20","country_id":"1","name":{"ar":"أبو حماد","en":"Abu Hammad"}},
                {"id":"313","state_id":"20","country_id":"1","name":{"ar":"القرين","en":"El Qurain"}},
                {"id":"314","state_id":"20","country_id":"1","name":{"ar":"ههيا","en":"Hehia"}},
                {"id":"315","state_id":"20","country_id":"1","name":{"ar":"أبو كبير","en":"Abu Kabir"}},
                {"id":"316","state_id":"20","country_id":"1","name":{"ar":"فاقوس","en":"Faccus"}},
                {"id":"317","state_id":"20","country_id":"1","name":{"ar":"الصالحية الجديدة","en":"El Salihia El Gedida"}},
                {"id":"318","state_id":"20","country_id":"1","name":{"ar":"الإبراهيمية","en":"Al Ibrahimiyah"}},
                {"id":"319","state_id":"20","country_id":"1","name":{"ar":"ديرب نجم","en":"Deirb Negm"}},
                {"id":"320","state_id":"20","country_id":"1","name":{"ar":"كفر صقر","en":"Kafr Saqr"}},
                {"id":"321","state_id":"20","country_id":"1","name":{"ar":"أولاد صقر","en":"Awlad Saqr"}},
                {"id":"322","state_id":"20","country_id":"1","name":{"ar":"الحسينية","en":"Husseiniya"}},
                {"id":"323","state_id":"20","country_id":"1","name":{"ar":"صان الحجر القبلية","en":"san alhajar alqablia"}},
                {"id":"324","state_id":"20","country_id":"1","name":{"ar":"منشأة أبو عمر","en":"Manshayat Abu Omar"}},
                {"id":"325","state_id":"21","country_id":"1","name":{"ar":"الطور","en":"Al Toor"}},
                {"id":"326","state_id":"21","country_id":"1","name":{"ar":"شرم الشيخ","en":"Sharm El-Shaikh"}},
                {"id":"327","state_id":"21","country_id":"1","name":{"ar":"دهب","en":"Dahab"}},
                {"id":"328","state_id":"21","country_id":"1","name":{"ar":"نويبع","en":"Nuweiba"}},
                {"id":"329","state_id":"21","country_id":"1","name":{"ar":"طابا","en":"Taba"}},
                {"id":"330","state_id":"21","country_id":"1","name":{"ar":"سانت كاترين","en":"Saint Catherine"}},
                {"id":"331","state_id":"21","country_id":"1","name":{"ar":"أبو رديس","en":"Abu Redis"}},
                {"id":"332","state_id":"21","country_id":"1","name":{"ar":"أبو زنيمة","en":"Abu Zenaima"}},
                {"id":"333","state_id":"21","country_id":"1","name":{"ar":"رأس سدر","en":"Ras Sidr"}},
                {"id":"334","state_id":"22","country_id":"1","name":{"ar":"كفر الشيخ","en":"Kafr El Sheikh"}},
                {"id":"335","state_id":"22","country_id":"1","name":{"ar":"وسط البلد كفر الشيخ","en":"Kafr El Sheikh Downtown"}},
                {"id":"336","state_id":"22","country_id":"1","name":{"ar":"دسوق","en":"Desouq"}},
                {"id":"337","state_id":"22","country_id":"1","name":{"ar":"فوه","en":"Fooh"}},
                {"id":"338","state_id":"22","country_id":"1","name":{"ar":"مطوبس","en":"Metobas"}},
                {"id":"339","state_id":"22","country_id":"1","name":{"ar":"برج البرلس","en":"Burg Al Burullus"}},
                {"id":"340","state_id":"22","country_id":"1","name":{"ar":"بلطيم","en":"Baltim"}},
                {"id":"341","state_id":"22","country_id":"1","name":{"ar":"مصيف بلطيم","en":"Masief Baltim"}},
                {"id":"342","state_id":"22","country_id":"1","name":{"ar":"الحامول","en":"Hamol"}},
                {"id":"343","state_id":"22","country_id":"1","name":{"ar":"بيلا","en":"Bella"}},
                {"id":"344","state_id":"22","country_id":"1","name":{"ar":"الرياض","en":"Riyadh"}},
                {"id":"345","state_id":"22","country_id":"1","name":{"ar":"سيدي سالم","en":"Sidi Salm"}},
                {"id":"346","state_id":"22","country_id":"1","name":{"ar":"قلين","en":"Qellen"}},
                {"id":"347","state_id":"22","country_id":"1","name":{"ar":"سيدي غازي","en":"Sidi Ghazi"}},
                {"id":"348","state_id":"23","country_id":"1","name":{"ar":"مرسى مطروح","en":"Marsa Matrouh"}},
                {"id":"349","state_id":"23","country_id":"1","name":{"ar":"الحمام","en":"El Hamam"}},
                {"id":"350","state_id":"23","country_id":"1","name":{"ar":"العلمين","en":"Alamein"}},
                {"id":"351","state_id":"23","country_id":"1","name":{"ar":"الضبعة","en":"Dabaa"}},
                {"id":"352","state_id":"23","country_id":"1","name":{"ar":"النجيلة","en":"Al-Nagila"}},
                {"id":"353","state_id":"23","country_id":"1","name":{"ar":"سيدي براني","en":"Sidi Brani"}},
                {"id":"354","state_id":"23","country_id":"1","name":{"ar":"السلوم","en":"Salloum"}},
                {"id":"355","state_id":"23","country_id":"1","name":{"ar":"سيوة","en":"Siwa"}},
                {"id":"356","state_id":"23","country_id":"1","name":{"ar":"مارينا","en":"Marina"}},
                {"id":"357","state_id":"23","country_id":"1","name":{"ar":"الساحل الشمالى","en":"North Coast"}},
                {"id":"358","state_id":"24","country_id":"1","name":{"ar":"الأقصر","en":"Luxor"}},
                {"id":"359","state_id":"24","country_id":"1","name":{"ar":"الأقصر الجديدة","en":"New Luxor"}},
                {"id":"360","state_id":"24","country_id":"1","name":{"ar":"إسنا","en":"Esna"}},
                {"id":"361","state_id":"24","country_id":"1","name":{"ar":"طيبة الجديدة","en":"New Tiba"}},
                {"id":"362","state_id":"24","country_id":"1","name":{"ar":"الزينية","en":"Al ziynia"}},
                {"id":"363","state_id":"24","country_id":"1","name":{"ar":"البياضية","en":"Al Bayadieh"}},
                {"id":"364","state_id":"24","country_id":"1","name":{"ar":"القرنة","en":"Al Qarna"}},
                {"id":"365","state_id":"24","country_id":"1","name":{"ar":"أرمنت","en":"Armant"}},
                {"id":"366","state_id":"24","country_id":"1","name":{"ar":"الطود","en":"Al Tud"}},
                {"id":"367","state_id":"25","country_id":"1","name":{"ar":"قنا","en":"Qena"}},
                {"id":"368","state_id":"25","country_id":"1","name":{"ar":"قنا الجديدة","en":"New Qena"}},
                {"id":"369","state_id":"25","country_id":"1","name":{"ar":"ابو طشت","en":"Abu Tesht"}},
                {"id":"370","state_id":"25","country_id":"1","name":{"ar":"نجع حمادي","en":"Nag Hammadi"}},
                {"id":"371","state_id":"25","country_id":"1","name":{"ar":"دشنا","en":"Deshna"}},
                {"id":"372","state_id":"25","country_id":"1","name":{"ar":"الوقف","en":"Alwaqf"}},
                {"id":"373","state_id":"25","country_id":"1","name":{"ar":"قفط","en":"Qaft"}},
                {"id":"374","state_id":"25","country_id":"1","name":{"ar":"نقادة","en":"Naqada"}},
                {"id":"375","state_id":"25","country_id":"1","name":{"ar":"فرشوط","en":"Farshout"}},
                {"id":"376","state_id":"25","country_id":"1","name":{"ar":"قوص","en":"Quos"}},
                {"id":"377","state_id":"26","country_id":"1","name":{"ar":"العريش","en":"Arish"}},
                {"id":"378","state_id":"26","country_id":"1","name":{"ar":"الشيخ زويد","en":"Sheikh Zowaid"}},
                {"id":"379","state_id":"26","country_id":"1","name":{"ar":"نخل","en":"Nakhl"}},
                {"id":"380","state_id":"26","country_id":"1","name":{"ar":"رفح","en":"Rafah"}},
                {"id":"381","state_id":"26","country_id":"1","name":{"ar":"بئر العبد","en":"Bir al-Abed"}},
                {"id":"382","state_id":"26","country_id":"1","name":{"ar":"الحسنة","en":"Al Hasana"}},
                {"id":"383","state_id":"27","country_id":"1","name":{"ar":"سوهاج","en":"Sohag"}},
                {"id":"384","state_id":"27","country_id":"1","name":{"ar":"سوهاج الجديدة","en":"Sohag El Gedida"}},
                {"id":"385","state_id":"27","country_id":"1","name":{"ar":"أخميم","en":"Akhmeem"}},
                {"id":"386","state_id":"27","country_id":"1","name":{"ar":"أخميم الجديدة","en":"Akhmim El Gedida"}},
                {"id":"387","state_id":"27","country_id":"1","name":{"ar":"البلينا","en":"Albalina"}},
                {"id":"388","state_id":"27","country_id":"1","name":{"ar":"المراغة","en":"El Maragha"}},
                {"id":"389","state_id":"27","country_id":"1","name":{"ar":"المنشأة","en":"almunshaa"}},
                {"id":"390","state_id":"27","country_id":"1","name":{"ar":"دار السلام","en":"Dar AISalaam"}},
                {"id":"391","state_id":"27","country_id":"1","name":{"ar":"جرجا","en":"Gerga"}},
                {"id":"392","state_id":"27","country_id":"1","name":{"ar":"جهينة الغربية","en":"Jahina Al Gharbia"}},
                {"id":"393","state_id":"27","country_id":"1","name":{"ar":"ساقلته","en":"Saqilatuh"}},
                {"id":"394","state_id":"27","country_id":"1","name":{"ar":"طما","en":"Tama"}},
                {"id":"395","state_id":"27","country_id":"1","name":{"ar":"طهطا","en":"Tahta"}},
                {"id":"396","state_id":"27","country_id":"1","name":{"ar":"الكوثر","en":"Alkawthar"}}

    ]';

        $citiesData = json_decode($jsonObject, true);
        foreach ($citiesData as $item) {
            DB::table('cities')->insert([
                'id' => $item['id'],
                'state_id' => $item['state_id'],
                'country_id' => $item['country_id'],
                'name' => json_encode($item['name']),
            ]);
        }

    }
}
